import { Eye, Pencil, Plus, Trash2 } from "lucide-react";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import api, { money } from "../api/client";
import { useDebounce } from "../hooks/useDebounce";
import { useUi } from "../context/UiContext";
import { EmptyState, Loader, Pagination, StatusBadge } from "../components/ui/Common";

const categories = ["Hotels", "Rooms", "Flights / Seats", "Transport", "Vehicles", "Travel Packages", "Tours", "Activities", "Visa Services", "Other"];
const title = (value) => String(value || "").replaceAll("_", " ");

export default function Inventory() {
  const { openModal, askConfirm } = useUi();
  const [q, setQ] = useState(""); const [category, setCategory] = useState(""); const [status, setStatus] = useState(""); const [availability, setAvailability] = useState(""); const [sort, setSort] = useState("newest"); const [page, setPage] = useState(1);
  const debounced = useDebounce(q);
  const summary = useQuery({ queryKey: ["inventory-summary"], queryFn: async () => (await api.get("/inventory/summary")).data });
  const list = useQuery({ queryKey: ["inventory", debounced, category, status, availability, sort, page], queryFn: async () => (await api.get("/inventory", { params: { q: debounced, category: category || undefined, status: status || undefined, availability: availability || undefined, sort, page, limit: 10 } })).data });
  const apply = (setter) => (event) => { setter(event.target.value); setPage(1); };
  const cards = [["Total Inventory", summary.data?.total_inventory, "text-brand-600"], ["Available", summary.data?.available, "text-emerald-600"], ["Reserved", summary.data?.reserved, "text-blue-600"], ["Low Availability", summary.data?.low_availability, "text-amber-600"], ["Out of Stock", summary.data?.out_of_stock, "text-red-600"]];
  return <div className="space-y-4">
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([label, value, color]) => <div className="card p-4" key={label}><p className="text-xs font-medium text-slate-400">{label}</p><p className={`mt-2 text-2xl font-extrabold ${color}`}>{value ?? "—"}</p></div>)}</div>
    <div className="card overflow-hidden"><div className="page-head"><div><h1 className="text-lg font-extrabold">Inventory</h1><p className="text-xs text-slate-400">Manage travel availability, reservations and supplier stock</p></div><button className="btn-primary" onClick={() => openModal("inventory")}><Plus className="h-4 w-4" /> Add Inventory</button></div>
      <div className="grid gap-2 border-t border-slate-100 p-4 sm:grid-cols-2 lg:grid-cols-5"><input className="input" placeholder="Search item, provider or destination..." value={q} onChange={apply(setQ)} /><select className="input" value={category} onChange={apply(setCategory)}><option value="">All categories</option>{categories.map((item) => <option key={item}>{item}</option>)}</select><select className="input" value={status} onChange={apply(setStatus)}><option value="">All statuses</option><option value="available">Available</option><option value="reserved">Reserved</option><option value="low_availability">Low availability</option><option value="out_of_stock">Out of stock</option><option value="inactive">Inactive</option></select><select className="input" value={availability} onChange={apply(setAvailability)}><option value="">All availability</option><option value="available">Available</option><option value="low">Low availability</option><option value="out">Out of stock</option></select><select className="input" value={sort} onChange={apply(setSort)}><option value="newest">Newest</option><option value="name">Name</option><option value="quantity">Total quantity</option><option value="available">Available quantity</option><option value="price">Selling price</option></select></div>
      {list.isPending && !list.data ? <Loader /> : !list.data?.data?.length ? <EmptyState title="No inventory found" hint="Add an item to manage its availability and reservations." /> : <div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-slate-50 text-left text-[11px] uppercase tracking-wide text-slate-400"><tr>{["Item", "Category", "Provider", "Destination", "Total", "Available", "Reserved", "Cost", "Selling Price", "Status", "Actions"].map((item) => <th className="px-4 py-3" key={item}>{item}</th>)}</tr></thead><tbody>{list.data.data.map((item) => <tr className="border-t border-slate-50" key={item.id}><td className="px-4 py-3 font-semibold">{item.name}</td><td className="px-4 py-3">{item.category}</td><td className="px-4 py-3">{item.supplier || "—"}</td><td className="px-4 py-3">{item.destination_name || "—"}</td><td className="px-4 py-3">{item.quantity}</td><td className="px-4 py-3 font-semibold text-emerald-600">{item.available_quantity}</td><td className="px-4 py-3">{item.reserved_quantity}</td><td className="px-4 py-3">{money(item.unit_cost)}</td><td className="px-4 py-3">{money(item.selling_price)}</td><td className="px-4 py-3"><StatusBadge value={title(item.status)} /></td><td className="px-4 py-3"><div className="flex gap-1"><button className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100" onClick={() => openModal("view-inventory", item)}><Eye className="h-4 w-4" /></button><button className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100" onClick={() => openModal("inventory", item)}><Pencil className="h-4 w-4" /></button><button className="rounded-lg p-1.5 text-red-500 hover:bg-red-50" onClick={() => askConfirm({ title: "Delete inventory item", message: `${item.name} will be permanently deleted. Bookings keep their history but will no longer link to this item.`, onConfirm: () => api.delete(`/inventory/${item.id}`) })}><Trash2 className="h-4 w-4" /></button></div></td></tr>)}</tbody></table></div>}
      {list.data?.data?.length ? <Pagination page={page} limit={10} total={list.data.total} onPage={setPage} /> : null}</div>
  </div>;
}
